name: 'Continuous integration'

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:

env:
  configuration: Release

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Call generator
        run: dotnet fsi GenerateLibs.fsx
        working-directory: './src'

      - name: Build solution
        run: dotnet build --nologo -c ${{ env.configuration }}
        working-directory: './src'

      - name: Verify code format
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: dotnet format --no-restore --verify-no-changes --exclude *.Generated.cs
        working-directory: './src'

      - name: Run unit tests
        run: dotnet test --no-restore -c ${{ env.configuration }} --filter TestCategory=UnitTest
        working-directory: './src'

      - name: Run integration tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: dotnet test --no-restore -c ${{ env.configuration }} --filter TestCategory=IntegrationTest
        working-directory: './src'